module.exports = {
  clearMocks: true,
  collectCoverage: true,
  coverageDirectory: 'coverage',
  verbose: true,
  preset: 'ts-jest',
  testEnvironment: 'jest-environment-node',
  testMatch: ['**/__tests__/**/*.unit.test.ts'],
  collectCoverageFrom: [
    'src/**/*.ts',
    '!src/**/index.ts',
    '!**/*.mock.ts',
    '!**/*.error.ts',
    '!**/*.errors.ts',
    '!**/__tests__/**',
    '!**/__mocks__/**',
    '!src/**/*.enums.ts',
    '!src/**/*.types.ts',
  ],
};
